### ISSUE TITLE
xml file is missing

### ISSUE THREAD

**Issue by MichaelUray** [torgrimt/zabbix-ntfy#1]
I actually don't see the xml file in the repository you mention in readme.md to add to Alerts -> Mediatypes.

**Comment by torgrimt** [comment]
Files get exported as yaml, and the file is here:
https://github.com/torgrimt/zabbix-ntfy/blob/main/zbx_ntfy.yaml

**Comment by MichaelUray** [comment]
Perfect, I already got it working.
