### ISSUE TITLE
Trouble enabling ntfy alerting for user in Zabbix

### ISSUE THREAD

**Issue by surfrock66** [torgrimt/zabbix-ntfy#12]
I'm using Zabbix 7.0.5.  I've installed the ntfy.sh media type, and have successfully sent the test message and received it in my ntfy instance.  I am only using URL, Topic, and Token as Parameters; I was assuming Message, Nseverity and Subject would come from the actual trigger.

When I go to enable the media for my user, I am prompted to populate a "Send To" field that is required; what is this supposed to be?  The params set in the media type options define where I'm sending notifications; there shouldn't need to be an additional item here.  Just as a test, I entered a single letter, or my email address, or my ntfy URL/Topic, but none of it changed if I received notifications or not. 
 I have created manual incidents (powered off a testing vm) and I get the email notifications, but not via ntfy:

![image](https://github.com/user-attachments/assets/61ea6047-6a2b-48fa-88f3-4cdf4bda4be9)

**Comment by surfrock66** [comment]
Close this, I rebooted my zabbix server and it started working.  As it is, I left it at "https://serverurl/topic" but I don't think that matters.

**Comment by rafaelorafaelo** [comment]
It's ntfy's topic feature https://docs.ntfy.sh/publish/
