### ISSUE TITLE
Error on import.

### ISSUE THREAD

**Issue by tbblake** [torgrimt/zabbix-ntfy#3]
When trying to import into a Zabbix 6.4.9 install I get this error:

Invalid tag "/zabbix_export/media_types/media_type(1)/parameters/parameter(4)/value": a character string is expected.

**Comment by torgrimt** [comment]
hmm. maybe it dosent like empty username/password. Or just to ""

**Comment by torgrimt** [comment]
@tbblake i made a new version supporting macros instead of hardcoded text. Imports fine now.

**Comment by tbblake** [comment]
Thanks!!
