### ISSUE TITLE
Send on Zabbix, not received on Ntfy

### ISSUE THREAD

**Issue by alexandremottier** [torgrimt/zabbix-ntfy#7]
Hi @torgrimt,

I tried your script today and I have a problem : I have configured the script as requested : 
![image](https://github.com/torgrimt/zabbix-ntfy/assets/40338703/f3bbdb34-061e-4090-a4c0-7db17f7bee2c)
I removed token, user and password as my server doesn't require authentication.

When I test the script, Zabbix is considering the message send, but no reception on my Ntfy server.
I tried to send message from CLI on Zabbix Server and it worked : 
![image](https://github.com/torgrimt/zabbix-ntfy/assets/40338703/e95c7a85-794d-4310-8f7e-334bfd4623de)

It looks like I missed something in the script configuration.
I'm running Zabbix 6.4.10. Thanks for your help 😊

**Comment by rafaelorafaelo** [comment]
Try with a value of 5 for Nseverity. Otherwise you could check Zabbix and ntfy.sh logs in debug log level.

**Comment by alexandremottier** [comment]
Simple as this ! Thanks a lot for your help @rafaelorafaelo !
![image](https://github.com/torgrimt/zabbix-ntfy/assets/40338703/81abd709-300f-4483-8a10-ff53df1d9696)

Have a nice day and thanks again ! 😉
